client library integration
fiskaly/fiskaly-sdk-node pull request #3
Opened 2020-06-08 18:45 UTC by mihajlon97

- client library
 - fiskalyServiceUrl optional parameter
 - tests adapted
 - readme updated

2020-06-09 09:12 UTC, pgaubatz commented on src/client/ClientLibrary.ts
> +            this.library = ffi.Library(`${__dirname}\\${this.getLibraryName()}`, {
this will most likely NOT work on non-windows platforms

2020-06-10 15:41 UTC, mihajlon97 commented on src/client/ClientLibrary.ts
> +            this.library = ffi.Library(`${__dirname}\\${this.getLibraryName()}`, {
Is the library path a problem?
Should we use require('path').join()?

2020-06-12 15:07 UTC, pgaubatz commented on src/client/ClientLibrary.ts
> +            this.library = ffi.Library(`${__dirname}\\${this.getLibraryName()}`, {
yes, please!

2020-06-12 15:20 UTC, pgaubatz requested changes

2020-06-12 15:20 UTC, pgaubatz commented on src/FiskalyClient.ts
> +            this.jsonRPC = jayson.Client.http(fiskalyServiceUrl);
how about:
```suggestion
            try {
                const lib = new ClientLibrary();
                this.doRequest = lib.request.bind(lib);
            } catch (e) {
                throw new FiskalyError("fiskalyServiceUrl must be provided");
            }
        } else {
            const rpc = jayson.Client.http(fiskalyServiceUrl);
            this.doRequest = rpc.request.bind(rpc);
```

these class fields can also be removed then:
```ts
    private jsonRPC: jayson.Client | undefined;
    private clientLibrary: ClientLibrary | undefined;
    private hasService: boolean = true;
```

instead there would only be:
```ts
    private doRequest: Function;
```

2020-06-12 16:46 UTC, pgaubatz requested changes
Re-add the following method:
```ts
    /**	
     * Send JSON RPC Request to Client	
     * @param {string} method	
     * @param {object} params	
     */	
    private async doRequest(method: string, params: object) {	
        if(!this.allowedMethods.includes(method)) {	
            throw new FiskalyError("Invalid method parameter");	
        }	
        const response = await this.doRequestFn(method, params);	
        /** Check if error exists */	
        if (response.error != null) {	
            throw FiskalyErrorHandler.throwError(response);	
        }	
        return response	
    }
```

2020-06-12 16:46 UTC, pgaubatz commented on src/FiskalyClient.ts
> +    private readonly doRequest: OmitThisParameter<(method: string, params: object) => Promise<JSONRPCResultLike> | null> = () => null;
```suggestion
    private readonly doRequestFn: OmitThisParameter<(method: string, params: object) => Promise<JSONRPCResultLike> | null> = () => null;
```

2020-06-12 16:46 UTC, pgaubatz commented on src/FiskalyClient.ts
> +    private hasService: boolean = true;
```suggestion
```

2020-06-12 16:46 UTC, pgaubatz commented on src/FiskalyClient.ts
> +                this.doRequest = lib.request.bind(lib);
```suggestion
                this.doRequestFn = lib.request.bind(lib);
```

2020-06-12 16:46 UTC, pgaubatz commented on src/FiskalyClient.ts
> +            this.doRequest = rpc.request.bind(rpc);
```suggestion
            this.doRequestFn = rpc.request.bind(rpc);
```

2020-06-12 16:46 UTC, pgaubatz commented on src/FiskalyClient.ts
> +        // @ts-ignore
```suggestion
```

2020-06-12 16:46 UTC, pgaubatz commented on src/FiskalyClient.ts
> +        }
```suggestion
```

2020-06-12 16:46 UTC, pgaubatz commented on src/FiskalyClient.ts
> +        }
```suggestion
```

2020-06-12 16:46 UTC, pgaubatz commented on src/FiskalyClient.ts
> +        }
```suggestion
```

2020-06-12 16:46 UTC, pgaubatz commented on src/FiskalyClient.ts
> +        }
```suggestion
```

2020-06-15 09:07 UTC, prempador requested changes

2020-06-15 09:07 UTC, prempador commented on tests/FiskalyClientTestClientLib.ts
> +    FISKALY_API_KEY = 'test_9b92hretadf7nbl9gotci0188_development';
Please don't have credentials in code.

2020-06-15 21:48 UTC, mihajlon97 commented on tests/FiskalyClientTestClientLib.ts
> +    FISKALY_API_KEY = 'test_9b92hretadf7nbl9gotci0188_development';
Fixed now with .env variables.

2020-08-11 12:29 UTC, prempador approved these changes

2020-08-11 12:29 UTC, merged